# Generated by Django 5.2.1 on 2025-06-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_pooling', '0002_remove_ridesegment_from_latitude_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RideSegment',
        ),
    ]
