# Generated by Django 5.2.1 on 2025-06-02 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_part', '0003_vehicletype_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_type', models.CharField(choices=[('now', 'Book Now'), ('scheduled', 'Scheduled')], max_length=10)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('from_location', models.CharField(max_length=255)),
                ('from_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('from_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('to_location', models.CharField(max_length=255)),
                ('to_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('to_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('offered_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('women_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_part.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_part.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='RideStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('order', models.PositiveIntegerField(help_text='Stop order')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_stops', to='rider_part.riderequest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
