# Generated by Django 5.2.1 on 2025-06-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_part', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
