# Generated by Django 5.2.1 on 2025-06-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_part', '0003_alter_riderequest_estimated_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='offered_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
