# Generated by Django 5.2.1 on 2025-06-17 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_part', '0006_riderequest_end_time_riderequest_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='rider_part.riderequest')),
            ],
        ),
    ]
