# Generated by Django 5.2.1 on 2025-06-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_part', '0007_rideotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideotp',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
