# Generated by Django 5.2.1 on 2025-06-18 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_part', '0009_ridepaymentdetail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ridepaymentdetail',
            name='driver_earnings',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual amount driver will earn from this ride (before platform fees if applicable)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ridepaymentdetail',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI')], max_length=20),
        ),
        migrations.CreateModel(
            name='DriverWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('ride_earning', 'Ride Earning'), ('adjustment', 'Manual Adjustment'), ('withdrawal', 'Withdrawal'), ('bonus', 'Bonus'), ('penalty', 'Penalty'), ('refund', 'Refund')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rider_part.riderequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
