# Generated by Django 5.2.1 on 2025-07-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_part', '0012_riderequest_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='ride_purpose',
            field=models.CharField(choices=[('official', 'Official'), ('personal', 'Personal')], default='personal', help_text='Whether this is a company-funded or personal ride', max_length=10),
        ),
    ]
