# Generated by Django 5.2.1 on 2025-07-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_part', '0013_riderequest_ride_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridepaymentdetail',
            name='upi_payment_id',
            field=models.CharField(blank=True, help_text='Transaction ID for UPI payments', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ridepaymentdetail',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('wallet', 'Wallet')], max_length=20),
        ),
    ]
