# Generated by Django 5.2.1 on 2025-07-10 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_part', '0014_ridepaymentdetail_upi_payment_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='employees',
            field=models.ManyToManyField(blank=True, help_text='Employees included in this corporate admin ride.', related_name='rides_as_passenger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='ride_purpose',
            field=models.CharField(choices=[('official', 'Official'), ('personal', 'Personal'), ('corporate_admin', 'Corporate Admin Booking')], default='personal', help_text='Whether this is a company-funded or personal ride', max_length=20),
        ),
    ]
