# Generated by Django 5.2.1 on 2025-07-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_part', '0015_riderequest_employees_alter_riderequest_ride_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverwallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('ride_earning', 'Ride Earning'), ('adjustment', 'Manual Adjustment'), ('withdrawal', 'Withdrawal'), ('bonus', 'Bonus'), ('penalty', 'Penalty'), ('refund', 'Refund'), ('Car pooling', 'Car pooling')], max_length=20),
        ),
    ]
