# Generated by Django 5.2.1 on 2025-07-25 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0026_rename_driverupipayment_sharedrideupipayment'),
        ('rider_part', '0017_driverwallettransaction_shared_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverwallettransaction',
            name='shared_ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ride_sharing.ridejoinrequest'),
        ),
    ]
