# Generated by Django 5.2.1 on 2025-07-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider_part', '0018_alter_driverwallettransaction_shared_ride'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverwallettransaction',
            old_name='shared_ride',
            new_name='shared_join_ride',
        ),
    ]
