# Generated by Django 5.2.1 on 2025-07-25 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_part', '0020_ridereportsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteToLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Custom name for this location', max_length=100)),
                ('to_location', models.CharField(max_length=255)),
                ('to_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('to_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_to_locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
