# Generated by Django 5.2.1 on 2025-07-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_part', '0022_ridereportsubmission_ride_share_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='require_otp',
            field=models.BooleanField(default=True, help_text='Whether OTP is needed for this ride'),
        ),
    ]
