# Generated by Django 5.2.1 on 2025-09-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_part', '0023_riderequest_require_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
