# Generated by Django 5.2.1 on 2025-09-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_part', '0027_emergencycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridepaymentdetail',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
