# Generated by Django 5.2.1 on 2025-09-30 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0029_remove_ridejoinrequest_message'),
        ('rider_part', '0028_ridepaymentdetail_gst_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpendingfee',
            name='shared_ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ride_sharing.ridesharebooking'),
        ),
        migrations.AlterField(
            model_name='driverpendingfee',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rider_part.riderequest'),
        ),
    ]
