# Generated by Django 5.2.1 on 2025-05-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='number_of_passengers',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of passengers allowed'),
        ),
    ]
