# Generated by Django 5.2.1 on 2025-05-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0002_vehicletype_number_of_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image representing this vehicle type', null=True, upload_to='vehicle_types/'),
        ),
    ]
