# Generated by Django 5.2.1 on 2025-06-12 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0003_vehicletype_image'),
        ('rider_part', '0006_riderequest_end_time_riderequest_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('flat', 'Flat'), ('percent', 'Percentage')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='₹ for flat, % for percentage', max_digits=5)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Applicable only for percentage discount', max_digits=6, null=True)),
                ('min_ride_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('usage_limit_per_user', models.PositiveIntegerField(default=1)),
                ('total_usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_part.promocode')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider_part.riderequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'promo_code', 'ride')},
            },
        ),
    ]
