# Generated by Django 5.2.1 on 2025-07-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0005_platformsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepaidPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('validity_days', models.PositiveIntegerField()),
                ('credits_provided', models.PositiveIntegerField(help_text='Credits given when the plan is purchased.')),
                ('is_active', models.BooleanField(default=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
