# Generated by Django 5.2.1 on 2025-07-25 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0007_alter_prepaidplan_validity_type'),
        ('rider_part', '0019_rename_shared_ride_driverwallettransaction_shared_join_ride'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='rider_part.riderequest')),
            ],
        ),
    ]
