# Generated by Django 5.2.1 on 2025-07-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0008_ridereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridereport',
            name='ride',
        ),
    ]
