# Generated by Django 5.2.1 on 2025-09-19 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0009_remove_ridereport_ride'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='is_active',
        ),
    ]
