# Generated by Django 5.2.1 on 2025-09-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0010_remove_promocode_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the support query category', max_length=100, unique=True)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Priority of the category (lower number = higher priority)')),
                ('description', models.TextField(blank=True, help_text='Optional description about this category', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
    ]
