# Generated by Django 5.2.1 on 2025-09-22 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0012_supportchat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportchat',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='supportchat',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='supportchat',
            name='message',
        ),
        migrations.AddField(
            model_name='supportchat',
            name='is_active',
            field=models.BooleanField(default=True, help_text='True if chat is ongoing'),
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='admin_part.supportchat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
