# Generated by Django 5.2.1 on 2025-09-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0013_alter_supportchat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='fee_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
