# Generated by Django 5.2.1 on 2025-06-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cash_payments_left',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
