# Generated by Django 5.2.1 on 2025-07-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0004_driverrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('rider', 'Rider'), ('driver', 'Driver'), ('corporate_admin', 'Corporate_Admin')], default='rider', max_length=20),
        ),
    ]
