# Generated by Django 5.2.1 on 2025-07-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0006_customuser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('rider', 'Rider'), ('driver', 'Driver'), ('corporate_admin', 'Corporate_Admin'), ('employee', 'Employee')], default='rider', max_length=20),
        ),
    ]
