# Generated by Django 5.2.1 on 2025-07-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0007_alter_customuser_role'),
        ('corporate_web', '0005_rename_purchases_plan_companyaccount_purchased_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='corporate_companies',
            field=models.ManyToManyField(blank=True, help_text='If not universal, assign specific corporate accounts', related_name='assigned_drivers', to='corporate_web.companyaccount'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='driver_type',
            field=models.CharField(blank=True, choices=[('normal', 'Normal Only'), ('corporate', 'Corporate Only'), ('both', 'Both')], help_text='Defines if the driver can do normal, corporate or both rides', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_universal_corporate_driver',
            field=models.BooleanField(default=False, help_text='Check this if driver can serve all corporate accounts'),
        ),
    ]
