# Generated by Django 5.2.1 on 2025-07-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0008_customuser_corporate_companies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='driver_type',
            field=models.CharField(blank=True, choices=[('normal', 'Normal Only'), ('corporate', 'Corporate Only'), ('both', 'Both')], default='normal', help_text='Defines if the driver can do normal, corporate or both rides', max_length=20, null=True),
        ),
    ]
