# Generated by Django 5.2.1 on 2025-07-18 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0010_customuser_is_corporate_driver'),
        ('ride_sharing', '0019_ridesharebooking_cancellation_probability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverrating',
            name='ride_sharing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_ratings', to='ride_sharing.ridesharebooking'),
        ),
    ]
