# Generated by Django 5.2.1 on 2025-07-25 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0011_driverrating_ride_sharing'),
        ('ride_sharing', '0026_rename_driverupipayment_sharedrideupipayment'),
        ('rider_part', '0019_rename_shared_ride_driverwallettransaction_shared_join_ride'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='driverrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='driverrating',
            name='ride_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_ratings', to='rider_part.riderequest'),
        ),
        migrations.AddConstraint(
            model_name='driverrating',
            constraint=models.UniqueConstraint(condition=models.Q(('ride_request', None), _negated=True), fields=('ride_request', 'driver'), name='unique_normal_ride_rating'),
        ),
        migrations.AddConstraint(
            model_name='driverrating',
            constraint=models.UniqueConstraint(condition=models.Q(('ride_sharing', None), _negated=True), fields=('ride_sharing', 'driver'), name='unique_shared_ride_rating'),
        ),
        migrations.RemoveField(
            model_name='driverrating',
            name='ride',
        ),
    ]
