# Generated by Django 5.2.1 on 2025-07-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0012_alter_driverrating_unique_together_and_more'),
        ('rider_part', '0019_rename_shared_ride_driverwallettransaction_shared_join_ride'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='driverrating',
            name='unique_normal_ride_rating',
        ),
        migrations.RemoveConstraint(
            model_name='driverrating',
            name='unique_shared_ride_rating',
        ),
        migrations.AlterUniqueTogether(
            name='driverrating',
            unique_together={('ride_request', 'driver')},
        ),
    ]
