# Generated by Django 5.2.1 on 2025-09-22 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0010_remove_promocode_is_active'),
        ('auth_api', '0016_alter_drivervehicleinfo_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivervehicleinfo',
            name='vehicle_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='admin_part.vehicletype'),
        ),
    ]
