# Generated by Django 5.2.1 on 2025-09-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0017_alter_drivervehicleinfo_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, default='Hubballi', help_text="Driver's city for ride assignment", max_length=100, null=True),
        ),
    ]
