# Generated by Django 5.2.1 on 2025-09-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0018_customuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='driver_cancellations_left',
            field=models.PositiveIntegerField(default=2, help_text='Number of free cancellations left for driver'),
        ),
    ]
