# Generated by Django 5.2.1 on 2025-07-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_web', '0003_companyprepaidplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccount',
            name='purchases_plan',
            field=models.BooleanField(default=False),
        ),
    ]
