# Generated by Django 5.2.1 on 2025-07-07 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_web', '0004_companyaccount_purchases_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyaccount',
            old_name='purchases_plan',
            new_name='purchased_plan',
        ),
    ]
