# Generated by Django 5.2.1 on 2025-07-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_web', '0005_rename_purchases_plan_companyaccount_purchased_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprepaidplan',
            name='total_credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
