# Generated by Django 5.2.1 on 2025-07-12 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_web', '0006_companyprepaidplan_total_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprepaidplan',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corporate_web.companyaccount'),
        ),
    ]
