# Generated by Django 5.2.1 on 2025-06-23 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideShareVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('model_name', models.CharField(max_length=100)),
                ('seat_capacity', models.PositiveIntegerField()),
                ('registration_doc', models.FileField(blank=True, null=True, upload_to='vehicle_docs/')),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to='ride_aadhar_cards/')),
                ('driving_license', models.FileField(blank=True, null=True, upload_to='ride_driving_licenses/')),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
