# Generated by Django 5.2.1 on 2025-06-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0003_ridejoinrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridesharevehicle',
            name='vehicle_number',
            field=models.CharField(max_length=20),
        ),
    ]
