# Generated by Django 5.2.1 on 2025-06-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0005_rename_available_seats_ride_seats_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
