# Generated by Django 5.2.1 on 2025-07-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0006_ride_price_per_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridesharevehicle',
            name='vehicle_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
