# Generated by Django 5.2.1 on 2025-07-14 12:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0007_alter_ridesharevehicle_vehicle_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideSharePriceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='ridejoinrequest',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='ridejoinrequest',
            name='user',
        ),
        migrations.CreateModel(
            name='RideShareBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('ride_date', models.DateField()),
                ('ride_time', models.TimeField()),
                ('passengers_count', models.PositiveIntegerField()),
                ('women_only', models.BooleanField(default=False)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_return_ride', models.BooleanField(default=False)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('return_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('return_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('passenger_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_share_bookings', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='ride_sharing.ridesharevehicle')),
            ],
        ),
        migrations.CreateModel(
            name='RideShareStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_location', models.CharField(max_length=255)),
                ('stop_distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stop_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.PositiveIntegerField(help_text='Order of the stop in the route')),
                ('ride_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='ride_sharing.ridesharebooking')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Ride',
        ),
        migrations.DeleteModel(
            name='RideJoinRequest',
        ),
    ]
