# Generated by Django 5.2.1 on 2025-07-14 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0008_ridesharepricesetting_remove_ridejoinrequest_ride_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridesharestop',
            name='stop_distance_km',
        ),
        migrations.RemoveField(
            model_name='ridesharestop',
            name='stop_price',
        ),
        migrations.AlterField(
            model_name='ridesharestop',
            name='order',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.CreateModel(
            name='RideShareRouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stop', models.CharField(max_length=255)),
                ('to_stop', models.CharField(max_length=255)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ride_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_segments', to='ride_sharing.ridesharebooking')),
            ],
        ),
    ]
