# Generated by Django 5.2.1 on 2025-07-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0010_ridesharebooking_from_location_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridesharestop',
            name='stop_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ridesharestop',
            name='stop_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
