# Generated by Django 5.2.1 on 2025-07-15 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0011_ridesharestop_stop_lat_ridesharestop_stop_lng'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RideSharePriceSetting',
        ),
    ]
