# Generated by Django 5.2.1 on 2025-07-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0012_delete_ridesharepricesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideSharePriceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
