# Generated by Django 5.2.1 on 2025-07-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0013_ridesharepricesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridesharebooking',
            name='seats_remaining',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
