# Generated by Django 5.2.1 on 2025-07-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0014_ridesharebooking_seats_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridesharebooking',
            name='to_location_estimated_arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ridesharestop',
            name='estimated_arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
