# Generated by Django 5.2.1 on 2025-07-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0016_ridejoinrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RideJoinRequest',
        ),
    ]
