# Generated by Django 5.2.1 on 2025-07-18 06:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0018_ridejoinrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ridesharebooking',
            name='cancellation_probability',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='RiderRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rated_by', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='rider_ratings_given', to=settings.AUTH_USER_MODEL)),
                ('ride_sharing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_ratings', to='ride_sharing.ridesharebooking')),
                ('rider', models.ForeignKey(limit_choices_to={'role': 'rider'}, on_delete=django.db.models.deletion.CASCADE, related_name='rider_ratings_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ride_sharing', 'rider', 'rated_by')},
            },
        ),
    ]
