# Generated by Django 5.2.1 on 2025-07-22 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0019_ridesharebooking_cancellation_probability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridesharebooking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='ride_sharing.ridesharevehicle'),
        ),
    ]
