# Generated by Django 5.2.1 on 2025-07-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0022_driverupipayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridesharebooking',
            name='reached_destination',
            field=models.BooleanField(default=False),
        ),
    ]
