# Generated by Django 5.2.1 on 2025-07-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0023_ridesharebooking_reached_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridesharestop',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
