# Generated by Django 5.2.1 on 2025-07-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0024_alter_ridesharestop_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridesharebooking',
            name='reached_destination',
        ),
    ]
