# Generated by Django 5.2.1 on 2025-07-24 12:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0025_remove_ridesharebooking_reached_destination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DriverUPIPayment',
            new_name='SharedRideUPIPayment',
        ),
    ]
