# Generated by Django 5.2.1 on 2025-07-25 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0026_rename_driverupipayment_sharedrideupipayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderrating',
            name='ride_sharing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_ratings', to='ride_sharing.ridejoinrequest'),
        ),
    ]
