# Generated by Django 5.2.1 on 2025-07-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0027_alter_riderrating_ride_sharing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridesharebooking',
            name='is_return_ride',
        ),
        migrations.RemoveField(
            model_name='ridesharebooking',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='ridesharebooking',
            name='return_distance_km',
        ),
        migrations.RemoveField(
            model_name='ridesharebooking',
            name='return_price',
        ),
        migrations.RemoveField(
            model_name='ridesharebooking',
            name='return_time',
        ),
    ]
