# Generated by Django 5.2.1 on 2025-07-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0028_remove_ridesharebooking_is_return_ride_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridejoinrequest',
            name='message',
        ),
    ]
