# Generated by Django 5.2.1 on 2025-09-30 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0030_sharedridepayment_delete_sharedrideupipayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedridepayment',
            name='join_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ride_sharing.ridejoinrequest'),
        ),
    ]
