# Generated by Django 5.2.1 on 2025-06-05 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('seating_capacity', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=20)),
                ('rental_price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_from_date', models.DateField()),
                ('available_to_date', models.DateField()),
                ('pickup_location', models.CharField(max_length=255)),
                ('vehicle_papers_document', models.FileField(upload_to='vehicle_documents/')),
                ('confirmation_checked', models.BooleanField(default=False)),
                ('vehicle_color', models.CharField(max_length=30)),
                ('is_ac', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
