# Generated by Django 5.2.1 on 2025-06-10 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_vehicle', '0006_rentalrequest_duration_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='HandoverChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handed_over_car_keys', models.BooleanField(default=False)),
                ('handed_over_vehicle_documents', models.BooleanField(default=False)),
                ('fuel_tank_full', models.BooleanField(default=False)),
                ('checklist_completed_at', models.DateTimeField(auto_now_add=True)),
                ('rental_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handover_checklist', to='rent_vehicle.rentalrequest')),
            ],
        ),
    ]
