# Generated by Django 5.2.1 on 2025-07-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_vehicle', '0007_alter_rentalrequest_status_handoverchecklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentedvehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rentedvehicle',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=20),
        ),
    ]
