# Generated by Django 5.2.1 on 2025-07-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_vehicle', '0008_alter_rentedvehicle_fuel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentedvehicle',
            name='bag_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
