# Generated by Django 5.2.1 on 2025-07-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_vehicle', '0009_rentedvehicle_bag_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentedvehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Sedan', 'Sedan')], max_length=100),
        ),
    ]
