# Generated by Django 5.2.1 on 2025-09-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_vehicle', '0010_alter_rentedvehicle_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('handovered', 'Handovered')], default='pending', max_length=20),
        ),
    ]
