# Generated by Django 5.2.1 on 2025-09-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FCMDevice',
        ),
    ]
